server:
  port: 8001



aliyun:
  mns:
   endpoint: xxx
   access-key-id: xxx
   access-key-secret: xxx
   config:
    id: abcdefg112233
   queue:
     - fyh-mns-queue
#     - fyh-mns-queue2
#     - fyh-mns-queue3